language: generic

matrix:
  include:
    # OSRF has bottles of Gazebo on Yosemite, so test gazebo_ros on that.
    - os: osx
      osx_image: xcode7
      env: ROS_DISTRO=indigo ROS_CONFIGURATION=gazebo_ros

    # Check up to rviz on El Capitan.
    - os: osx
      osx_image: xcode8
      env: ROS_DISTRO=indigo ROS_CONFIGURATION=rviz

    # Kinetic currently fails due to qt4/5 issues.
    - os: osx
      osx_image: xcode8
      env: ROS_DISTRO=kinetic ROS_CONFIGURATION=ros_base

  allow_failures:
    - env: ROS_DISTRO=kinetic ROS_CONFIGURATION=ros_base

script:
  - ./install
